blank_issues_enabled: false
contact_links:
  - name: ğŸš€ ì´ìŠˆ ìƒì„±
    url: https://github.com/soohwan93/mainProject-Team4/issues/new?template=issue_template.md
    about: ìƒˆë¡œìš´ ê¸°ëŠ¥ì´ë‚˜ ì‘ì—…ì„ ìœ„í•œ ì´ìŠˆë¥¼ ìƒì„±í•©ë‹ˆë‹¤